stages:
  - test

test:lint:composer:
  stage: test
  image: in2code/php:7.2-fpm
  script:
    - composer validate --strict

test:lint:typoscript:
  stage: test
  image: in2code/typo3-typoscript-lint:7.2
  script:
    - typoscript-lint -c .typoscript-lint.yml

test:lint:php-7.4:
  stage: test
  image: php:7.4-cli
  script:
    - find ./ -path ./.Build -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php -l -n > /dev/null

test:lint:php-8.0:
  stage: test
  image: php:8.0-cli
  script:
    - find ./ -path ./.Build -prune -false -o -type f -name '*.php' -print0 | xargs -0 -n1 -P$(nproc) php -l -n > /dev/null

test:phpcs:
  stage: test
  image: in2code/phpcs:7.2
  script:
    - phpcs

test:phpmd:
  stage: test
  image: in2code/phpmd:7.2
  script:
    - phpmd Classes ansi .phpmd.xml
