services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  CoStack\Logs\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  CoStack\Logs\Log\Eraser\EraserCollection:
    factory: [ '@CoStack\Logs\Factory\CollectionFactory', 'createEraserCollection' ]

  CoStack\Logs\Log\Reader\ReaderCollection:
    factory: [ '@CoStack\Logs\Factory\CollectionFactory', 'createReaderCollection' ]
